{
  "_comment": "Starter brand/domain lookup for mention extraction. Add every brand you want tracked here — a brand not listed can still be matched by name in the AI Mode summary text, but won't be matched against reference/citation domains, which is the stronger signal. Keep domains lowercase, no protocol.",
  "CeraVe": "cerave.com",
  "The Ordinary": "theordinary.com",
  "Aesop": "aesop.com",
  "La Roche-Posay": "laroche-posay.us",
  "EltaMD": "eltamd.com",
  "Paula's Choice": "paulaschoice.com",
  "Drunk Elephant": "drunkelephant.com",
  "Kiehl's": "kiehls.com",
  "Tatcha": "tatcha.com",
  "Sunday Riley": "sundayriley.com",
  "AG1": "drinkag1.com",
  "Bloom Nutrition": "bloomnu.com",
  "Ritual": "ritual.com",
  "Care/of": "careof.com",
  "Thorne": "thorne.com",
  "Pure Encapsulations": "pureencapsulations.com",
  "Momentous": "livemomentous.com",
  "Optimum Nutrition": "optimumnutrition.com",
  "Lululemon": "lululemon.com",
  "Alo Yoga": "aloyoga.com",
  "Vuori": "vuoriclothing.com",
  "Rhone": "rhone.com",
  "Gymshark": "gymshark.com",
  "Nike": "nike.com"
}
